### ISSUE TITLE
CUXD

### ISSUE THREAD

**Issue by joeduck** [tzahari/CCU-Historian-for-Docker#2]
Hi,

i use 0.7.6hf1 on DSM 5.2. How can i use CUXD Devices? It seems that the config File ist not recgnized!?

Many Thanks.

**Comment by tzahari** [comment]
Hi Joeduck,
Sorry, for my late answer.
You can modify the config within the docker container and add anything / modify you want. 
It might be easier if you export the config folder out of the container.
Hope I could help you.
Best Regards Thomas

**Comment by tzahari** [comment]
Hi Joeduck,
Is this issue solved?
Best Regards
Thomas

**Comment by tzahari** [comment]
no response... closing

**Comment by joeduck** [comment]
Sorry, forgot this post. Issue is solved. Many thanks.
