### ISSUE TITLE
Timezone parameter for jar-startup

### ISSUE THREAD

**Issue by TheMiller2015** [tzahari/CCU-Historian-for-Docker#3]
Hello,

thanks for your great work. I switched to your docker-image today. I saw in start.sh, that you don't pass the timezone-parameter for the java startup command.

I would like to have an ENV-Variable (e.g. JAVA_TIMEZONE) that would be passed to start start-command. 

My Server/Host has Europe/Berlin CEST 13:03:00, but the Historian WebGUI shows 11:03:00.

Could you implement this globally for your images? Don't want to make my own on your base.

Many thanks, again!

**Comment by TheMiller2015** [comment]
Ah okay, I solved it by adding the env-variable "TZ" with the value "Europe/Berlin". In my case, I added it to docker-compose. Others may start the container with the -e parameter.

Thanks anyway.

**Comment by tzahari** [comment]
You're welcome. :-) Thanks for the info.

Best Regards Thomas
