### ISSUE TITLE
CCU-Historian 1.1.0 stable

### ISSUE THREAD

**Issue by timokli** [tzahari/CCU-Historian-for-Docker#4]
Any plans to upgrade your docker image to CCU-Historian 1.1.0 stable? Would be great :)

**Comment by tzahari** [comment]
Yes I will do. 
But there are a lot of changes and also the Java Docker image is outdated. 
I need some more time to fix and change the stuff.

**Comment by timokli** [comment]
dont hurry :)

**Comment by tzahari** [comment]
Hi Timokli,
It is finally done with the commit f8e71ca5e72bb0b7f7d187b726db13af1560ed0d
So feel free to update.
Best Regards Thomas
