### ISSUE TITLE
Timeout on interface BidCos-RF and no more graphs

### ISSUE THREAD

**Issue by x-jokay** [tzahari/CCU-Historian-for-Docker#5]
Hi

First I want to thank you for this docker-container :)

Since the update to v1.1.0 it shows only SysVar values but no more BidCosRF values on the overview and the graphs are gone.

On the logs I can see the following message:
"WARNING|Timeout on interface(s) BidCos-RF, HmIP-RF, CUxD; reinitializing all callbacks"

I have removed the database and started with only a config.php

Are there any new config params which need to be set for v1.1.0 to work?

**Comment by x-jokay** [comment]
And some more logs regarding the graphs:
SEVERE |Exception: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
SEVERE |Exception: Could not initialize class org.jfree.chart.JFreeChart

**Comment by x-jokay** [comment]
config.php from v1.0.0 is obviously not compatible with v1.1.0 due to the renaming of params.

But even after using the new params there are no BidCos-RF, HmIP-RF and CUxD values, only SysVar values.

**Comment by x-jokay** [comment]
Got it to work for the values, but the problem with the missing graphs remains.

**Comment by tzahari** [comment]
Hi x-jokay,
Thanks for your report. 
I found also this problem and opened a bug at ccu-historian mdzio/ccu-historian#71
I switched the Java JRE from Sun/Oracle JRE to OpenJDK cause there is no official Oracle JRE Docker image. 

But It seems, that the class path from the manifest file is not used correctly. 
I tried to fix it with a0dec90fd7578ac64c5a5f8a3658e8d2517b0d25 but it also does not work.

Best Regards Thomas

**Comment by x-jokay** [comment]
OpenJDK would be very nice :)

**Comment by x-jokay** [comment]
May be you could give it a try using this?

java **-Djava.awt.headless=true** -jar ...

**Comment by tzahari** [comment]
Should be fixed with the commit 825dd756abbcefabb5c1ec2b888dc7482895ace7
Best Regards Thomas

**Comment by x-jokay** [comment]
Great, thank you.
