### ISSUE TITLE
Update Docker image

### ISSUE THREAD

**Issue by Xento** [tzahari/CCU-Historian-for-Docker#8]
Can you provide an updated docker image for version 1.2.0

**Comment by tzahari** [comment]
I pushed a new version https://github.com/tzahari/CCU-Historian-for-Docker/commit/5ba157997a79c9384e001a80abdde2632625280c and the docker is now available.
Small note: I had to delete the ccu historian database, otherwise I saw a lot of exceptions in the log file.
